version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgre-db
    restart: always
    environment:
      POSTGRES_DB: application_db
      POSTGRES_USER: application_user
      POSTGRES_PASSWORD: application_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
